export const TEMPLATES = [
  {
    id: 'professional',
    name: 'Professional',
    layout: 'centered',
    styles: {
      primaryColor: '#8b5cf6',
      secondaryColor: '#6d28d9',
      bgColor: '#0a0a0f',
      font: 'Inter',
      cornerStyle: 'rounded',
      spacing: 'normal',
    },
  },
  {
    id: 'creative',
    name: 'Creative',
    layout: 'cover',
    styles: {
      primaryColor: '#ec4899',
      secondaryColor: '#f97316',
      bgColor: '#0f0a1e',
      font: 'Inter',
      cornerStyle: 'rounded',
      spacing: 'relaxed',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    layout: 'left',
    styles: {
      primaryColor: '#6b7280',
      secondaryColor: '#9ca3af',
      bgColor: '#111118',
      font: 'Inter',
      cornerStyle: 'sharp',
      spacing: 'compact',
    },
  },
  {
    id: 'bold',
    name: 'Bold',
    layout: 'centered',
    styles: {
      primaryColor: '#ef4444',
      secondaryColor: '#f97316',
      bgColor: '#0a0a0a',
      font: 'Inter',
      cornerStyle: 'sharp',
      spacing: 'normal',
    },
  },
  {
    id: 'elegant',
    name: 'Elegant',
    layout: 'centered',
    styles: {
      primaryColor: '#f59e0b',
      secondaryColor: '#d97706',
      bgColor: '#0c0c0e',
      font: 'Inter',
      cornerStyle: 'rounded',
      spacing: 'relaxed',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    layout: 'left',
    styles: {
      primaryColor: '#3b82f6',
      secondaryColor: '#1d4ed8',
      bgColor: '#030712',
      font: 'Inter',
      cornerStyle: 'rounded',
      spacing: 'normal',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    layout: 'cover',
    styles: {
      primaryColor: '#f97316',
      secondaryColor: '#ec4899',
      bgColor: '#0f0a05',
      font: 'Inter',
      cornerStyle: 'rounded',
      spacing: 'relaxed',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    layout: 'centered',
    styles: {
      primaryColor: '#06b6d4',
      secondaryColor: '#0284c7',
      bgColor: '#020d1a',
      font: 'Inter',
      cornerStyle: 'rounded',
      spacing: 'normal',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    layout: 'left',
    styles: {
      primaryColor: '#22c55e',
      secondaryColor: '#16a34a',
      bgColor: '#020d05',
      font: 'Inter',
      cornerStyle: 'rounded',
      spacing: 'normal',
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    layout: 'centered',
    styles: {
      primaryColor: '#a855f7',
      secondaryColor: '#06b6d4',
      bgColor: '#01010a',
      font: 'Inter',
      cornerStyle: 'sharp',
      spacing: 'compact',
    },
  },
  {
    id: 'rose',
    name: 'Rose',
    layout: 'cover',
    styles: {
      primaryColor: '#f43f5e',
      secondaryColor: '#fb7185',
      bgColor: '#100005',
      font: 'Inter',
      cornerStyle: 'rounded',
      spacing: 'relaxed',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    layout: 'left',
    styles: {
      primaryColor: '#64748b',
      secondaryColor: '#475569',
      bgColor: '#0a0c10',
      font: 'Inter',
      cornerStyle: 'sharp',
      spacing: 'normal',
    },
  },
];

export const getTemplate = (id) => TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
